version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      # Below are env vars passed to the container
      - AUTH_SERVICE_URL=${AUTH_SERVICE_URL}
      - EXTERNAL_CHECK_USER_URL=${EXTERNAL_CHECK_USER_URL}
      - EXTERNAL_API_KEY=${EXTERNAL_API_KEY}
      - JWT_SECRET=${JWT_SECRET}
      - FIREBASE_PROJECT_ID=${FIREBASE_PROJECT_ID}
      - FIREBASE_CLIENT_EMAIL=${FIREBASE_CLIENT_EMAIL}
      - FIREBASE_PRIVATE_KEY=${FIREBASE_PRIVATE_KEY}
    restart: unless-stopped
